/* Drop if exists */
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS users;

/* Create tables */
CREATE TABLE recipes (
    id SERIAL PRIMARY KEY,
    title VARCHAR(30),
    img VARCHAR(50),
    video VARCHAR(80),
    time INT,
    serving INT,
    description VARCHAR(80),
    ingredients TEXT,
    instructions TEXT,
    tags VARCHAR(20)
);

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(80),
    email VARCHAR(80)
);

CREATE TABLE userRecipes (
    id SERIAL PRIMARY KEY,
    userId INT,
    recipeId int,
    FOREIGN KEY (userId) REFERENCES users(id),
    FOREIGN KEY (recipeId) REFERENCES recipes(id)
);

/* Inserts */
INSERT INTO recipes ("id", "title", "img", "video", "time", "serving", "description", "ingredients", "instructions", "tags") VALUES
(1, 'Char Sui', './img/recipes/charsui.jpg', 'https://www.youtube.com/embed/MPZ5fw35bc4', 30, 4, 'The perfect roast for a family gathering', '2 lb Pork Shoulder. 2 Cubes Red Bean Curd. 1 Tbsp Red Bean Curd Juice. 2 Tbsp Hoisin. 2 Tbsp Soy Sauce. 2 Tbsp Chinese Cooking Wine (optional). 1 Tbsp sesame Oil. 2 Tbsp Honey. 1 Tbsp Five Spice Powder. 1/4 tsp White Pepper. 2 Cloves of Garlic. 2 Tbsp Honey. 2-3 tsp Red Bean Curd Juice', 'In a bowl, combine your marinade ingredients. Mince or grate your garlic in the bowl and mix. If you don''t have cloves of garlic, minced garlic from a jar works also. In a large bowl or container, pour marinade onto the pork shoulder. Make sure to cover every part of the pork including the bottom. Put the bowl or container in the fridge and let it marinate for a day, for better results marinate for 2 days. Onto a grilling rack, place the marinated pork. Create a honey glaze by combining 2 Tbsp of Honey and 2-3 tsps of red bean curd juice. With the oven heated at 375 degrees. Put the pork in for 15 minutes. After you take out the pork, glaze it with an oil brush (make sure to also glaze the bottom). Every 5 to 7 minutes, reglaze the pork. Do this 2 to 3 times. Once pork is cooked through, let it rest before serving or storing it in the fridge for later', 'chinese'),
(2, 'Mapo Tofu', './img/recipes/mapo_tofu.jpg', 'https://www.youtube.com/embed/yRCs5sIJ2NU', 30, 2, 'Tastes like home', '1 lb Ground Pork (turkey, chicken, or beef). 400 Grams Tofu (softer the better). Green Onions. 1 Tbsp of Ginger. 3 Cloves of Garlic, 1 Tbsp Doubanjiang. 1 Tbsp Mirin. 1 Tbsp Oyster Sauce. 1 Tbsp Soy Sauce. 1 Cup Water. 1 Tbsp of Potato Starch (corn starch works too). Vegetable oil. 2 Cups of Chicken Stock', 'In a bowl, combine the doubanjiang, mirin, oyster sauce and soy sauce. Mince the garlic cloves, ginger and chop up the green onions and set aside. Cut the tofu into 1 in cubes. Make sure ground pork is soft by either defrosting it or putting it in the fridge overnight. Grab a wok and bring the temperature to medium heat (you can also use a large pot but make sure to bring the temperature to high heat first). Add some vegetable oil, wait for a min and then add your condiments, stir so the ingredients don’t stick. Once the aroma starts to release from the condiments, add in your ground meat and sauce. Combine well and make sure to break apart the larger pieces of your meat. Once the meat is cooked, add your chicken stock and reduce heat. While your ingredients are being brought to a boil, combine and stir your potato starch and water. After the chicken stock is boiling, add your tofu and potato starch slurry. Make sure to combine the ingredients, but not too harshly so that you don''t break up the tofu', 'chinese'),
(3, 'Fried Rice', './img/recipes/fried_rice.jpg', 'https://www.youtube.com/embed/Dk0axPbD2pc?si=jLvz_0OgrrVDpCxZ', 30, 2, 'Delicious and easy recipe for a chill family dinner', '2 Eggs. 2 Boneless Chicken Thighs. 1 Cup Chopped Ham. 1/2 Cup Shiitake Mushrooms Chopped. 2 Cloves of Garlic Crushed. 1/2 Pound of Frozen Peas. 3 Tbsp Soy Sauce. 3 Tbsp Oyster Sauce. Sesame Seeds. 4 1/2 Cups of Cooked Rice (Prefered Cold). Salt. Vegetable Oil. 1 Tbsp Butter', 'Pre heat pan to medium heat and add vegetable oil. Beat the eggs and while the pan is heating and add them when it reaches temperature. Once eggs are semi cooked, remove them from heat and add the rest of the butter. Remove eggs, add more oil to pan and add protein of choice. Once the protein is semi cooked, remove from the pan, clean it and add more oil. Throw in Shiitake mushrooms to let them brown a little and then throw in peas and chopped ham. Saute the ingredients until the chopped ham is a little brown, add your leftover rice and then the soy and oyster sauces. Turn to high heat and mix ingredients in pan until well mix. Incorporate your protein and eggs to the stir fry. While mixing, add in some vegetable oil, scallions and some sesame seeds. Turn to low heat and add butter to add richness to stir fry', 'chinese'),
(4, 'Pot Stickers', './img/recipes/potstickers.jpg', 'https://www.youtube.com/embed/iC1rvXPt_rE', 30, 2, 'Perfect for packed lunches', '1 lb Ground Pork. 1 Cup Shredded green Cabbage. 3 Ounces Shiitake Mushrooms. 2 Cloves Garlic. 2 Green Onions. 1 Tbsp Hoisin. 1 Tbsp Freshly Grated Ginger. 2 tsp Sesame Oil. 1/4 teaspoon White Pepper. 1 Cup Soy Sauce. 1 Cup Rice Vinegar. 1 tsp Sesame Oil. 1 Tbsp Chili Oil. 1 Clove of Garlic. 36 Wonton Wrappers. Water', 'In a bowl, combine pork, cabbage, mushrooms, garlic, green onions, hoisin, ginger, sesame oil, and white pepper. For each dumpling, place a Tbsp of the filling at the center of each wrapper. With your finger, rub the edges with water then fold the wrapper in a moon shape. Pinch the edges to seal. To make the sauce, mince your garlic and add your ingredients together (you can also use minced garlic). Heat vegetable oil in a large skillet over medium heat. Add your pot stickers to the skillet and cook until golden crisp, about 2-3 minutes per side.', 'chinese'),
(5, 'Tea Eggs', './img/recipes/tea_eggs.jpg', 'https://www.youtube.com/embed/NNDyuZ0RsEs', 30, 4, 'Easy meal preping', '10 Grams of Chinese Black Tea Leaves (can also use tea bags). 3 Pieces of Star Anise. 3 Bay Leaves. 3 Cloves of Garlic. 1 Stalk of Cinnamon. 1 1/2 tsp of Five Spice Powder. 1 Cup of Soy Sauce. 2 tbsp of Dark Soy Sauce. 1 tbsp of Salt. 8 Cups of Water', 'In a pot, add all the ingredients except for the eggs. Cover it and turn the heat to high. Once the water starts to boil, turn down the heat to low and cook for another 15 minutes. Pour some of the brine into a smaller sauce pan that has the eggs. This should be enough to cover the tea eggs. Put back the smaller pot onto the stove and boil for 2 minutes. While the eggs are cooking, cover the large pot and cool it by putting it into the fridge. Once the eggs are done cooking, place the eggs in an ice bath to stop them from over cooking. With a spoon, lightly crack the egg shell without breaking the eggs. After the eggs are cracked, place them back into the small pot, which then they will be boiled for another 4 minutes. After the 4 minutes, place the eggs into the larger pot of brine and marinate them for 4 hours. Going above 4 hours will infuse more of the flavor in the egg.', 'chinese,vegetarian'),
(6, 'Japanese Curry', './img/recipes/japanese_chicken_curry.jpg', 'https://www.youtube.com/embed/_0yTwf3eJAA', 30, 2, '', '2 lbs of Boneless Chicken Thighs.30 grams of Ginger.4 Cloves of Garlic. 1 teaspoon salt.1/4 Cup Water.1/8 tsp Baking Soda.2 Large Onions.5 Carrots.4 Cups of Vegtable Stock.1 Banana.2 Medium Potatoes.1 Bay Leaf.1 Star Anise.2 Tbsps Soy Sauce.1 Tbsp Chunou Sauce.1 Tbsp Tomato Paste.2 tsps Cocoa Powder.3 Tbsps Japanese Curry Powder (You can also make your own)', 'Dice up 4 carrots and 2 potatoes into cubes, and chop up 2 onions.In a small bowl, mix together 1/4 cup of water with baking soda to make a baking soda solution.In a different bowl, grate your garlic and ginger. In a different bowl, grate your last carrot.Cut your chicken into cubes while cutting off the excess fat on the sides.Heat up a large pot to medium heat and put some vegetable oil in it. Fry chicken in oil until brown on each side, usually 3 minutes per side.Once browning is done, remove chicken and set it aside.In the pot, add your grated ginger and garlic.Once there is some burnt residue in the pot, add your onions and baking soda solution.After ingredients are mixed, reduce heat to low, cover the pot and wait for 10 minutes.After 10 minutes, uncover pot and stir your caramelized onions until the water is mostly gone.Add in your grated carrots and continue to mix until mixture is glossy brown. Usually it takes 15 minutes after the cover is removed.Add in your curry powder and mix. Make sure to continuously mix so that the powder doesn''t burn.Once you can smell the powder, pour in your vegetable stock, a banana, and puree the mixture with a hand blender.Puree the mixture until it becomes a smooth and thick blend.Then add your soy sauce, tomato paste, chuno sauce, a star anise, a bay leaf, your chicken, and your vegetables. Let the ingredients simmer until 1 hour later or when the vegetables are soft.Before the curry is cooked, add in your cocoa powder.', 'japanese'),
(7, 'Gyudon', './img/recipes/gyudon.jpg', 'https://www.youtube.com/embed/LdeXSCcnJFY', 30, 2, '', '1/2 lb Thinly Sliced Beef.15 Grams Ginger.1 Medium Onion. 20 Grams Sugar.90 ml Sake.30 ml Soy Sauce.Vegetable Oil.Salt.750 ml Water.1 Piece of Dried Kelp (Kombu)', 'Slice beef into half or bite sized pieces.Slice an onion and break apart the pieces. Do it against the grain so that it cooks faster.Slice your ginger as thin as possible. To make kombu dashi, fill a pot with 750 ml of water and place your dried kelp in it. For better results, let the dried kelp soak in the water for an hour or even overnight.Warm the pot at low heat until it starts to boil. Then take it off the heat.Heat a pot up to medium heat and put some vegetable oil.Then add ginger and cook until it is soft and aromatic.Add your onion and a pinch of salt. Cook it until the onions become translucent.Add the kombu dashi, sugar, and let it boil.Add the beef and sake.Once the mixture is boiling again, remove half of the scum.At the end, add your soy sauce and let it simmer for 10-15 minutes', 'japanese'),
(8, 'Katsudon', './img/recipe/katsudon.jpg', 'https://www.youtube.com/embed/yGhgQgjVhGA', 30, 2, '', '1/2 lb Pork Loin.1/2 of an Onion.2 Eggs.1 tsp Sugar.4 tsp Soy Sauce.2 tsp Sake.1 tsp Mirin.1 Piece of Dried Kelp (Kombu).50 Grams salt.1 Piece of Dried Kelp (Kombu).100 ml Water.Flour.Black Pepper.Egg.Panko Crumbs.Vegetable Oil', 'Take your pork loin and cut off the skin if there is any.Add cuts between the fat and meat so that the meat doesn''t curl when frying.Use the back of the knife to tenderize the meat.Don''t use a spiked mallet, it will make the pork loose moisture.Slice up half an onion and break apart the pieces.Mince 5 grams of ginger and set aside.In a blender, blend up a piece of dried kelp and 50 grams of salt.After blended, use a strainer to remove the larger bits of the dried kelp.Combine 1/3 tsp of Kombu salt and 1/6 tsp of sugar.Use the mixture to season your pork by rubbing and covering the pork. Afterward, leave it for an hour.While your pork is resting, combine 1 piece of dried kelp with 100 ml of water to make dashi. Let it soak for at least an hour better overnight.In the same bowl of your dashi, add 1 tsp of sugar, 4 tsp of soy sauce, 2 tsp of sake, and 1 tsp of mirin.Combine the ingredients well.Once the pork is done marinating, coat the pork in flour, egg, and lastly panko crumbs.Heat a pan with vegetable oil to medium heat and add 5 grams of minced ginger.Once the ginger is aromatic, add in your onions and add a pinch of kombu salt. Saute on medium heat for 3 minutes.Once soft, add in your sauce. and boil for 30 seconds. Afterward take it off the heat and let it rest.In a separate pot, bring vegetable oil to 350 F, 180 - 183 C, and fry your pork for about 3 minutes. Let the pork dry and rest on a sheet of paper towel or drying rack.While your pork is resting, reheat your sauce on low heat.Cut your pork into strips and dip them in the extra sauce. Set them aside afterward.Bring your pan with sauce and onions to high heat, and add your eggs. Wait for a moment before scrambling them gently', 'japanese'),
(9, 'Oyakodon', './img/recipes/oyakodon.jpg', 'https://www.youtube.com/embed/iChssoYXsuA', 30, 2, '', '1/3 lb of Chicken Thigh (can also use chicken breast just not as flavorful).1/2 of an Onion.5 Grams Ginger.2 Eggs.50 ml Water.1 tsp Sugar.4 tsp Soy Sauce.2 tsp Sake.1 tsp Mirin.1 Dried Kelp (Konbu)', 'Slice chicken into cubes.Slice an onion and break apart the pieces. Do it against the grain so that it cooks faster.Mince your ginger into a bowl.Beat 2 eggs in a bowl. Make sure they''re lightly beaten and not completely mixed.To make your sauce, mix together 50 ml of water, 1 tsp sugar, 4 tsp soy sauce, 2 tsp sake, 1 tsp mirin, and 1 dried kelp.Marinate your chicken in the sauce and leave it for 30 to 40 minutes.Heat a pan with vegetable oil to medium heat and add 5 grams of minced ginger.Once the ginger is aromatic, add in your onions and add a pinch of salt. Saute on medium heat for 3 minutes.Once soft, take the pan off the heat for 5 minutes.Add the kombu dashi, sugar, and let it boil.Put the pan back on low heat, and add in your sauce and chicken. Slowly boil your sauce to release more flavor.After the sauce begins to boil, add in your eggs. Do not touch it, it will be cooked in seconds.At the end, shake the pan a little and with a utensil bring in the eggs to the center with a couple of strokes', 'japanese'),
(10, 'Tempura Udon', './img/recipes/tempura_udon.jpg', 'https://www.youtube.com/embed/iigDXgdKkuI', 30, 2, '', '1 Carrot.1 Eggplant.2 Pieces Shrimp.900 ml Water.10g Dried Kelp (Kombu).20 Grams Dried Sardines.20 Grams Thick Bonito Flakes.5 Grams Thin Bonito Flakes.110 Grams Tempura Flour.1 Egg.Water.300 Grams Flour.140 ml Water.15 Grams Salt.1 tsp of Soy Sauce.Salt', 'For your noodles, sift your flour and add some water with salt dissolved in it.Knead the flour to make dough and then put it in a bag to step on it.Once the dough is flat, fold and repeat the process a few more times. Then let it rest. Shred your carrot into slices.With your eggplant, you can either just chop it into large circles or you can fan it.Take your shrimp, cut off the tip of the tail and squeeze the liquid out.Then cut the muscle strips with a knife and press so that it doesn''t curl when frying.Once the dough has rested for an hour, spread some flour on a surface and flatten your dough with a rolling pin till it becomes a large flat sheet. Make sure the dough also has flour on it.Once flat, fold your dough and chop it to make noodles. You can also use a pasta machine.In a pot, add 20 grams of dry sardines, a piece of dried kelp, water and bring it to a boil.Right before it boils, remove your sardines and dried kelp, and replace it with thick bonito flakes. Let it boil for a few minutes.Turn the burner off and add thin bonito flakes. Wait for 5 minutes until they all sink.Filter the soup through a paper towel.Once filtered, add 1 tsp of Soy Sauce and a pinch of salt.Add water to a bowl of tempura flour and coat your toppings in it.Deep fry them in vegetable oil at 350 F, or 180 C.Lastly boil your noodles in water for 10 minutes', 'japanese');

INSERT INTO users ("id", "username", "email") VALUES
(1, 'Caleb', 'caleb.y.xu@gmail.com'),
(2, 'John', 'john445@gmail.com');

INSERT INTO userRecipes ("userid", "recipeid") VALUES
(1, 1);

/* General */
ALTER TABLE recipes
ALTER COLUMN video
TYPE VARCHAR(80);

ALTER TABLE users
ALTER COLUMN id
TYPE SERIAL;

UPDATE recipes
SET img = (
    SELECT REPLACE(img, 'fried_rice.jpg', 'charsui.jpg') as img from recipes
)
WHERE id = 1;

UPDATE recipes
SET img = 'mapo_tofu.jpg'
WHERE id = 2;