/* Nextjs imports */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Kameron } from 'next/font/google';
/* General imports */
import "../css/globals.css";
import "../css/normalize.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import ClientWrapper from './ClientWrapper';


// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

const kameron = Kameron({
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: '/img/umaiOrangeLogo.svg'
    }
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

    return (
        <GoogleOAuthProvider clientId="630460929969-47is0aidbr8r9jitmhd12v3m6000875b.apps.googleusercontent.com">
            <html lang="en">
                <link rel="icon" href="/favicon.ico" sizes="any" />
                <body className={kameron.className}>
                    <ClientWrapper>
                        {children}
                    </ClientWrapper>
                </body>
            </html>
        </GoogleOAuthProvider>
    );
}
