/* Nextjs imports */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Kameron } from 'next/font/google';
/* React imports */
import { createContext } from 'react';
import { useState } from 'react';
/* General imports */
import "../css/globals.css";
import "../css/normalize.css";
import NavBar from '../components/NavBar';
import { GoogleOAuthProvider } from '@react-oauth/google';

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

const kameron = Kameron({
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const [responsePayload, setResponsePayload] = useState<string>('');

    return (
        <GoogleOAuthProvider clientId="630460929969-47is0aidbr8r9jitmhd12v3m6000875b.apps.googleusercontent.com">
            <html lang="en">
                <body className={kameron.className}>
                    <NavBar setResponsePayload={setResponsePayload} />
                    {children}
                </body>
            </html>
        </GoogleOAuthProvider>
    );
}
